source :rubygems

group :development, :test do
  gem 'httparty', '>=0.4.3'
  gem 'minitest'
  gem 'ruby-debug', :platforms => 'ruby_18'
  gem 'ruby-debug19', :require => 'ruby-debug', :platforms => 'ruby_19'
  gem 'webmock'
end
